### ISSUE TITLE
Installing raspbian on linux

### ISSUE THREAD

**Issue by ADepic** [BigOokie/SkiPi#1]
I couldn't flash NOOBS using linux. Etcher just said the file was incomatible.

To flash on linux I had to:

1. Download a piece of softawre called [etcher](https://etcher.io/) 
2. Download [raspbian lite](https://www.raspberrypi.org/downloads/raspbian/)
3. In etcher, choose your sd card as the drive and your raspbian lite zip file as the image, adn then let it flash. Please list your current flashing tutorial under the header "Windows and Mac" and add seperate GNU/linux header

**Comment by BigOokie** [comment]
Thanks for the feedback. The official Raspberry Pi site provide details for installing the Raspbian OS as well as NOOBs.
https://www.raspberrypi.org/learning/software-guide/quickstart/

In my personal experience (I use MacOS), and as per the instructions provided on the site, I downloaded the NOOBs zip file, extracted it to my local machine and then simply copied the files onto a FAT32 formatted SD card. I then inserted that SD card into the RasPi and booted it.  I didn't actually need Etcher other other disk imaging software to do this.
