### ISSUE TITLE
enable ssh access

### ISSUE THREAD

**Issue by ADepic** [BigOokie/SkiPi#2]
Change the instruction "enable ssh access"

to

"enable ssh access (interfacing options > SSH > Yes > ok)"

**Comment by BigOokie** [comment]
When I wrote the HOWTO originally I assumed readers would be reasonably experienced with Linux, and RasPi. Over time and based on feedback I have been filling in the gaps - so appreciate the feedback. Will add the suggested change in.

**Comment by BigOokie** [comment]
Howto has been updated to address the feedback
