### ISSUE TITLE
Go install not working

### ISSUE THREAD

**Issue by ADepic** [BigOokie/SkiPi#5]
The last step for installing skywire is 
`go install ./...`
Last time I used that command, it was stuck for 15 minutes.
I did CTRL-C and tried again, it worked, however it lead to other issues (such as flashing search services box and missing node key at the bottom of the node settings in skywire manager).
Then I reflashing raspbian lite & tried again, this time doing `go install -v ./...` and I got the output.

It seems that it is stuck on [github.com/skycoin/skywire/vendor/github.com/skycoin/net/factory
](https://github.com/skycoin/skywire/tree/master/vendor/github.com/skycoin/net/factory).

This is a 10kb folder, so I don't see how it is stuck for 10 minutes.

Since this is the last day for whitelisting, I will miss the whitelisting if this doesn't get fixed.

**Comment by BigOokie** [comment]
I see you closed the issue? Did you get it working.  

Presumably it’s not an issue with the guide as such.

I have noticed that if the RasPi (3B+) is not adequately powered, it can be very slow and can actually boot you out of a remote SSH connection. One of mine has been doing this when building.
